applications:
  - name: selim.config-client
    memory: 1G
    instances: 1
    routes: 
      - route: selim-config-client.apps.tst-dc1.yapikredi.com.tr
    services:
      - DOCUMENT.EDISON-TST.ConfigServer
    env:
      JAVA_OPTS: -Duser.timezone=Europe/Istanbul
      SPRING_CLOUD_CONFIG_LABEL: tst